services:
  nexus:
    build:
      context: ./DOB-nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
  runner:
    build:
      context: ./DOB-runner
    environment:
      - GH_OWNER=${GH_OWNER}
      - GH_REPOSITORY=${GH_REPOSITORY}
      - GH_TOKEN=${GH_TOKEN}

volumes:
  nexus-data:
